sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - downloads

env:
  global:
    - JACKRABBIT_VERSION=2.12.0
    - SYMFONY__PHPCR__TRANSPORT=doctrinedbal
    - TEST_FLAGS=""
    - SYMFONY__DATABASE__DRIVER=pdo_mysql

matrix:
  include:
    - php: 5.6
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.0
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction
        - SYMFONY__DATABASE__DRIVER=pdo_pgsql
        - SYMFONY__DATABASE__USER=postgres
        - SYMFONY__DATABASE__PASSWORD=postgres
        - SYMFONY__PHPCR__TRANSPORT=jackrabbit
        # restart jackrabbit after each suite see: https://github.com/sulu-io/sulu/issues/2137
        - TEST_FLAGS="--jackrabbit-restart"

# Sqlite support: https://github.com/sulu/sulu/issues/2048
# Postgres support: https://github.com/sulu/sulu/issues/2241
#
#    - php: 7.0
#      env:
#        - SYMFONY__DATABASE__DRIVER=pdo_sqlite
#        - SYMFONY__DATABASE__PATH=test.sqlite
#    - php: 7.0
#      env: 
#        - SYMFONY__DATABASE__DRIVER=pdo_pgsql
#        - SYMFONY__DATABASE__USER=postgres
#        - SYMFONY__DATABASE__PASSWORD=postgres
#  fast_finish: true # do not wait for allowed failures, as they do not affect the build.

before_script:
  - if [ ! -d downloads ]; then mkdir downloads; fi
  - |
    if [[ $SYMFONY__PHPCR__TRANSPORT = jackrabbit ]]; then 
        if [ ! -f downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar ]; then 
            cd downloads
            wget http://archive.apache.org/dist/jackrabbit/$JACKRABBIT_VERSION/jackrabbit-standalone-$JACKRABBIT_VERSION.jar
            cd -
        fi
        java -jar downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar > /dev/null &
    fi
  # the content tests are intensive and there are memory leaks, this is more pronounced with the Jackalope DBAL PHPCR implementation.
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update $COMPOSER_FLAGS
  - if [[ $SYMFONY__PHPCR__TRANSPORT = jackrabbit ]]; then composer require jackalope/jackalope-jackrabbit:^1.2 ; fi

script: 
  - time ./bin/runtests -i -a $TEST_FLAGS

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
